# Generated by Django 2.2 on 2019-04-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=10)),
                ('ename', models.CharField(max_length=20)),
                ('eaddress', models.CharField(max_length=30)),
            ],
        ),
    ]
